/**
 * 全部 API 文档
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AlipayCreateOrderWapPayRequest { 
    /**
     * 自定义订单号
     */
    orderNo: string;
    /**
     * 订单金额。例如：0.01
     */
    amount: number;
    /**
     * 商品名称
     */
    subject: string;
    /**
     * 支付完成后返回的URL地址
     */
    returnUrl?: string | null;
}


