/**
 * 全部 API 文档
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 应用设置
 */
export interface AppSetting { 
    /**
     * 唯一标识
     */
    id?: number;
    /**
     * 提供商代码
     */
    providerCode?: string | null;
    /**
     * 分组代码
     */
    groupCode?: string | null;
    /**
     * 设置项代码
     */
    code: string;
    /**
     * 设置值
     */
    value: string;
    /**
     * 标签
     */
    tags?: string | null;
    /**
     * 描述
     */
    description?: string | null;
    /**
     * 是否在前端可用
     */
    frontendUsable?: boolean;
    /**
     * 创建时间
     */
    createDate?: string;
    /**
     * 最后更新时间
     */
    lastUpdate?: string;
}


