/**
 * 全部 API 文档
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MySqlGeometry } from './mySqlGeometry';


/**
 * 地理位置
 */
export interface GeoLocation { 
    /**
     * 唯一标识
     */
    id?: number;
    /**
     * 业务代码
     */
    bizCode: string;
    /**
     * 业务ID
     */
    bizID: number;
    coordinates: MySqlGeometry;
    /**
     * 地点的名称
     */
    locationName?: string | null;
    /**
     * 地点类型
     */
    locationType?: string | null;
    /**
     * 收货人姓名
     */
    recipientName?: string | null;
    /**
     * 收货人联系电话
     */
    phoneNumber?: string | null;
    /**
     * 收货人电子邮件
     */
    email?: string | null;
    /**
     * 国家
     */
    country?: string | null;
    /**
     * 州/省
     */
    state?: string | null;
    /**
     * 城市
     */
    city?: string | null;
    /**
     * 区/县
     */
    district?: string | null;
    /**
     * 街道
     */
    street?: string | null;
    /**
     * 邮政编码
     */
    zipCode?: string | null;
    /**
     * 详细的地址信息
     */
    address?: string | null;
    /**
     * 地址类型
     */
    mapType?: string | null;
    /**
     * 备注
     */
    remark?: string | null;
    /**
     * 标签
     */
    tags?: string | null;
    /**
     * 是否启用
     */
    enable?: boolean;
    /**
     * 排序索引
     */
    showIndex?: number;
    /**
     * 创建时间
     */
    createDate?: string;
    /**
     * 最后更新时间
     */
    lastUpdate?: string;
}


