/**
 * 全部  API 文档
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PhoneSignInRequest { 
    phone: string;
    verifyCode: string;
    /**
     * 如果启用双因素认证登录，则必填
     */
    twoFactorCode?: string | null;
}


