/**
 * 全部  API 文档
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ServiceProvider { 
    id?: number;
    bizCode?: string | null;
    name?: string | null;
    code?: string | null;
    icon?: string | null;
    description?: string | null;
    tags?: string | null;
    show?: boolean;
    showIndex?: number;
    createDate?: string;
    lastUpdate?: string;
}


