/**
 * 全部 API 文档
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServiceSettingGroupPostResult } from './serviceSettingGroupPostResult';


export interface ServiceSettingGroupPostResultApiResponse { 
    /**
     * 状态码
     */
    code?: number;
    data?: ServiceSettingGroupPostResult;
    /**
     * 错误信息
     */
    error?: string | null;
}


