/**
 * 全部 API 文档
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServiceItem } from './serviceItem';


export interface ServiceItemListApiResponse { 
    /**
     * 状态码
     */
    code?: number;
    /**
     * 响应数据
     */
    data?: Array<ServiceItem> | null;
    /**
     * 错误信息
     */
    error?: string | null;
}


