/**
 * 全部 API 文档
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TradeSettleDetail { 
    amount?: string | null;
    operationDt?: string | null;
    operationSerialNo?: string | null;
    operationType?: string | null;
    oriTransIn?: string | null;
    oriTransOut?: string | null;
    transIn?: string | null;
    transOut?: string | null;
}


