/**
 * 全部 API 文档
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserMutualFollowersResult } from './userMutualFollowersResult';


export interface UserMutualFollowersResultApiResponse { 
    /**
     * 状态码
     */
    code?: number;
    data?: UserMutualFollowersResult;
    /**
     * 错误信息
     */
    error?: string | null;
}


