/**
 * 全部 API 文档
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 用户配置实体，用于存储用户的个性化设置。
 */
export interface UserSetting { 
    /**
     * 用户的唯一标识符。
     */
    id?: number;
    /**
     * 关联的用户ID，表示该配置属于哪个用户。
     */
    userID: number;
    /**
     * 提供商的唯一代码，用于标识服务提供者。
     */
    providerCode?: string | null;
    /**
     * 组的唯一代码，用于分类设置项。
     */
    groupCode?: string | null;
    /**
     * 设置项的唯一代码或键名，用于标识具体的配置项。
     */
    code: string;
    /**
     * 设置项的具体值或选项。
     */
    value: string;
    /**
     * 用于对设置项进行分类或标记的标签。
     */
    tags?: string | null;
    /**
     * 设置项的详细描述，说明其作用或用途。
     */
    description?: string | null;
    /**
     * 指示该设置项是否在前端界面中可用。
     */
    frontendUsable?: boolean;
    /**
     * 设置项的创建时间。
     */
    createDate?: string;
    /**
     * 设置项的最后更新时间。
     */
    lastUpdate?: string;
}


