/**
 * 全部  API 文档
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FollowerModel } from './followerModel';


export interface UserFollowingResult { 
    totalFollowers?: number;
    data?: Array<FollowerModel> | null;
}


