/**
 * 全部 API 文档
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContributeDetail } from './contributeDetail';


export interface VoucherDetail { 
    amount?: string | null;
    id?: string | null;
    memo?: string | null;
    merchantContribute?: string | null;
    name?: string | null;
    otherContribute?: string | null;
    otherContributeDetail?: Array<ContributeDetail> | null;
    purchaseAntContribute?: string | null;
    purchaseBuyerContribute?: string | null;
    purchaseMerchantContribute?: string | null;
    templateId?: string | null;
    type?: string | null;
}


