export * from './accessToken.service';
import { AccessTokenService } from './accessToken.service';
export * from './accessToken.serviceInterface';
export * from './alipay.service';
import { AlipayService } from './alipay.service';
export * from './alipay.serviceInterface';
export * from './app.service';
import { AppService } from './app.service';
export * from './app.serviceInterface';
export * from './dingTalk.service';
import { DingTalkService } from './dingTalk.service';
export * from './dingTalk.serviceInterface';
export * from './externalAccount.service';
import { ExternalAccountService } from './externalAccount.service';
export * from './externalAccount.serviceInterface';
export * from './file.service';
import { FileService } from './file.service';
export * from './file.serviceInterface';
export * from './oAuth.service';
import { OAuthService } from './oAuth.service';
export * from './oAuth.serviceInterface';
export * from './order.service';
import { OrderService } from './order.service';
export * from './order.serviceInterface';
export * from './storage.service';
import { StorageService } from './storage.service';
export * from './storage.serviceInterface';
export * from './user.service';
import { UserService } from './user.service';
export * from './user.serviceInterface';
export * from './userCurrency.service';
import { UserCurrencyService } from './userCurrency.service';
export * from './userCurrency.serviceInterface';
export * from './userFriends.service';
import { UserFriendsService } from './userFriends.service';
export * from './userFriends.serviceInterface';
export * from './userLocation.service';
import { UserLocationService } from './userLocation.service';
export * from './userLocation.serviceInterface';
export * from './wechat.service';
import { WechatService } from './wechat.service';
export * from './wechat.serviceInterface';
export const APIS = [AccessTokenService, AlipayService, AppService, DingTalkService, ExternalAccountService, FileService, OAuthService, OrderService, StorageService, UserService, UserCurrencyService, UserFriendsService, UserLocationService, WechatService];
