export * from './accessToken.service';
import { AccessTokenService } from './accessToken.service';
export * from './accessToken.serviceInterface';
export * from './alipay.service';
import { AlipayService } from './alipay.service';
export * from './alipay.serviceInterface';
export * from './app.service';
import { AppService } from './app.service';
export * from './app.serviceInterface';
export * from './appSetting.service';
import { AppSettingService } from './appSetting.service';
export * from './appSetting.serviceInterface';
export * from './authorizePolicy.service';
import { AuthorizePolicyService } from './authorizePolicy.service';
export * from './authorizePolicy.serviceInterface';
export * from './currency.service';
import { CurrencyService } from './currency.service';
export * from './currency.serviceInterface';
export * from './dingTalk.service';
import { DingTalkService } from './dingTalk.service';
export * from './dingTalk.serviceInterface';
export * from './file.service';
import { FileService } from './file.service';
export * from './file.serviceInterface';
export * from './oAuth.service';
import { OAuthService } from './oAuth.service';
export * from './oAuth.serviceInterface';
export * from './order.service';
import { OrderService } from './order.service';
export * from './order.serviceInterface';
export * from './project.service';
import { ProjectService } from './project.service';
export * from './project.serviceInterface';
export * from './serviceSetting.service';
import { ServiceSettingService } from './serviceSetting.service';
export * from './serviceSetting.serviceInterface';
export * from './storage.service';
import { StorageService } from './storage.service';
export * from './storage.serviceInterface';
export * from './team.service';
import { TeamService } from './team.service';
export * from './team.serviceInterface';
export * from './tenant.service';
import { TenantService } from './tenant.service';
export * from './tenant.serviceInterface';
export * from './tenantFile.service';
import { TenantFileService } from './tenantFile.service';
export * from './tenantFile.serviceInterface';
export * from './user.service';
import { UserService } from './user.service';
export * from './user.serviceInterface';
export * from './userCurrency.service';
import { UserCurrencyService } from './userCurrency.service';
export * from './userCurrency.serviceInterface';
export * from './userSetting.service';
import { UserSettingService } from './userSetting.service';
export * from './userSetting.serviceInterface';
export * from './wechat.service';
import { WechatService } from './wechat.service';
export * from './wechat.serviceInterface';
export const APIS = [AccessTokenService, AlipayService, AppService, AppSettingService, AuthorizePolicyService, CurrencyService, DingTalkService, FileService, OAuthService, OrderService, ProjectService, ServiceSettingService, StorageService, TeamService, TenantService, TenantFileService, UserService, UserCurrencyService, UserSettingService, WechatService];
