/**
 * 全部 API 文档
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { App } from '../model/models';
import { AppApiResponse } from '../model/models';
import { AppCheckVersionResultApiResponse } from '../model/models';
import { AppInfoResultApiResponse } from '../model/models';
import { AppListResultApiResponse } from '../model/models';
import { AppPostResultApiResponse } from '../model/models';
import { BooleanApiResponse } from '../model/models';
import { SetupCodeApiResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AppRequestParams {
    appKey: string;
}

export interface App2FARequestParams {
    appKey: string;
}

export interface App2FACheckRequestParams {
    appKey: string;
    code?: string;
}

export interface AppCheckVersionRequestParams {
    appKey: string;
    checkOnly?: boolean;
}

export interface AppDeleteRequestParams {
    appKey: string;
}

export interface AppInfoRequestParams {
    appKey: string;
    propCode?: string;
}

export interface AppPostRequestParams {
    app?: App;
}

export interface AppPutRequestParams {
    appKey: string;
    app?: App;
}

export interface AppTransferRequestParams {
    appKey: string;
    projectId?: number;
}

export interface AppsRequestParams {
    projectId?: number;
    skip?: number;
    take?: number;
}


export interface AppServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 应用详情
     * 根据应用Key获取应用的详细信息。
* @param requestParameters
     */
    app(requestParameters: AppRequestParams, extraHttpRequestParams?: any): Observable<AppApiResponse>;

    /**
     * 双因素验证 获取
     * 获取应用的双因素验证信息。
* @param requestParameters
     */
    app2FA(requestParameters: App2FARequestParams, extraHttpRequestParams?: any): Observable<SetupCodeApiResponse>;

    /**
     * 双因素验证 验证
     * 验证应用的双因素验证代码。
* @param requestParameters
     */
    app2FACheck(requestParameters: App2FACheckRequestParams, extraHttpRequestParams?: any): Observable<BooleanApiResponse>;

    /**
     * 更新应用数据库
     * 检查应用数据库的版本，如果有未应用的迁移且checkOnly为false，则应用这些迁移。
* @param requestParameters
     */
    appCheckVersion(requestParameters: AppCheckVersionRequestParams, extraHttpRequestParams?: any): Observable<AppCheckVersionResultApiResponse>;

    /**
     * 删除应用
     * 根据应用Key删除应用。
* @param requestParameters
     */
    appDelete(requestParameters: AppDeleteRequestParams, extraHttpRequestParams?: any): Observable<BooleanApiResponse>;

    /**
     * 应用详情
     * 根据应用Key获取应用的详细信息和属性。
* @param requestParameters
     */
    appInfo(requestParameters: AppInfoRequestParams, extraHttpRequestParams?: any): Observable<AppInfoResultApiResponse>;

    /**
     * 创建应用
     * 创建一个新的应用。
* @param requestParameters
     */
    appPost(requestParameters: AppPostRequestParams, extraHttpRequestParams?: any): Observable<AppPostResultApiResponse>;

    /**
     * 更新应用
     * 根据应用Key更新应用信息。
* @param requestParameters
     */
    appPut(requestParameters: AppPutRequestParams, extraHttpRequestParams?: any): Observable<BooleanApiResponse>;

    /**
     * 转移应用
     * 将应用转移到另一个项目。
* @param requestParameters
     */
    appTransfer(requestParameters: AppTransferRequestParams, extraHttpRequestParams?: any): Observable<AppApiResponse>;

    /**
     * 应用列表
     * 根据项目ID获取应用列表，支持分页。
* @param requestParameters
     */
    apps(requestParameters: AppsRequestParams, extraHttpRequestParams?: any): Observable<AppListResultApiResponse>;

}
