/**
 * 全部 API 文档
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BooleanApiResponse } from '../model/models';
import { FileListResultApiResponse } from '../model/models';
import { StringApiResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface FileCreateFolderRequestParams {
    appKey: string;
    path?: string;
}

export interface FileDeleteRequestParams {
    appKey: string;
    path?: string;
}

export interface FileRenameRequestParams {
    appKey: string;
    sourceName?: string;
    destName?: string;
}

export interface FileUploadRequestParams {
    appKey: string;
    path?: string;
    file?: Blob;
}

export interface FilesRequestParams {
    appKey: string;
    path?: string;
    skip?: number;
    take?: number;
}


export interface FileServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 创建文件夹
     * 在指定路径创建文件夹
* @param requestParameters
     */
    fileCreateFolder(requestParameters: FileCreateFolderRequestParams, extraHttpRequestParams?: any): Observable<BooleanApiResponse>;

    /**
     * 删除文件 / 文件夹
     * 根据指定路径删除文件或文件夹
* @param requestParameters
     */
    fileDelete(requestParameters: FileDeleteRequestParams, extraHttpRequestParams?: any): Observable<BooleanApiResponse>;

    /**
     * 重命名文件 / 文件夹
     * 将指定的文件或文件夹重命名
* @param requestParameters
     */
    fileRename(requestParameters: FileRenameRequestParams, extraHttpRequestParams?: any): Observable<BooleanApiResponse>;

    /**
     * 上传文件
     * 将文件上传到指定路径
* @param requestParameters
     */
    fileUpload(requestParameters: FileUploadRequestParams, extraHttpRequestParams?: any): Observable<StringApiResponse>;

    /**
     * 获取文件列表
     * 根据指定路径获取文件和文件夹列表
* @param requestParameters
     */
    files(requestParameters: FilesRequestParams, extraHttpRequestParams?: any): Observable<FileListResultApiResponse>;

}
