/**
 * 全部 API 文档
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BooleanApiResponse } from '../model/models';
import { GeoLocationModel } from '../model/models';
import { GeoLocationModelApiResponse } from '../model/models';
import { UserLocationPostResultApiResponse } from '../model/models';
import { UserLocationsResultApiResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface UserLocationRequestParams {
    id: number;
    appKey: string;
    userId?: string;
}

export interface UserLocationDeleteRequestParams {
    id: number;
    appKey: string;
    userId?: string;
}

export interface UserLocationPostRequestParams {
    appKey: string;
    userId?: string;
    geoLocationModel?: GeoLocationModel;
}

export interface UserLocationPutRequestParams {
    id: number;
    appKey: string;
    userId?: string;
    geoLocationModel?: GeoLocationModel;
}

export interface UserLocationsRequestParams {
    appKey: string;
    tag?: string;
    type?: string;
    x?: number;
    y?: number;
    sphere?: number;
    skip?: number;
    take?: number;
    userId?: string;
}


export interface UserLocationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 获取位置详情
     * 根据位置ID获取位置详情
* @param requestParameters
     */
    userLocation(requestParameters: UserLocationRequestParams, extraHttpRequestParams?: any): Observable<GeoLocationModelApiResponse>;

    /**
     * 删除位置
     * 根据位置ID删除位置信息
* @param requestParameters
     */
    userLocationDelete(requestParameters: UserLocationDeleteRequestParams, extraHttpRequestParams?: any): Observable<BooleanApiResponse>;

    /**
     * 添加位置
     * 添加新的位置信息
* @param requestParameters
     */
    userLocationPost(requestParameters: UserLocationPostRequestParams, extraHttpRequestParams?: any): Observable<UserLocationPostResultApiResponse>;

    /**
     * 更新位置
     * 此方法用于更新指定位置ID的位置信息。如果位置不存在，则创建一个新的位置。
* @param requestParameters
     */
    userLocationPut(requestParameters: UserLocationPutRequestParams, extraHttpRequestParams?: any): Observable<BooleanApiResponse>;

    /**
     * 获取位置列表
     * 根据条件获取位置列表
* @param requestParameters
     */
    userLocations(requestParameters: UserLocationsRequestParams, extraHttpRequestParams?: any): Observable<UserLocationsResultApiResponse>;

}
