/**
 * 全部 API 文档
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BooleanApiResponse } from '../model/models';
import { UserSetting } from '../model/models';
import { UserSettingApiResponse } from '../model/models';
import { UserSettingListApiResponse } from '../model/models';
import { UserSettingPostResultApiResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface UserSettingRequestParams {
    id: number;
    appKey: string;
}

export interface UserSettingDeleteRequestParams {
    id: number;
    appKey: string;
}

export interface UserSettingPostRequestParams {
    appKey: string;
    userSetting?: UserSetting;
}

export interface UserSettingPutRequestParams {
    id: number;
    appKey: string;
    userSetting?: UserSetting;
}

export interface UserSettingsRequestParams {
    appKey: string;
    userId?: number;
    code?: string;
    tag?: string;
}


export interface UserSettingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 获取用户配置项详情
     * 根据配置项ID获取用户配置项详情
* @param requestParameters
     */
    userSetting(requestParameters: UserSettingRequestParams, extraHttpRequestParams?: any): Observable<UserSettingApiResponse>;

    /**
     * 删除用户配置项
     * 根据配置项ID删除用户配置项
* @param requestParameters
     */
    userSettingDelete(requestParameters: UserSettingDeleteRequestParams, extraHttpRequestParams?: any): Observable<BooleanApiResponse>;

    /**
     * 添加用户配置项
     * 添加新的用户配置项
* @param requestParameters
     */
    userSettingPost(requestParameters: UserSettingPostRequestParams, extraHttpRequestParams?: any): Observable<UserSettingPostResultApiResponse>;

    /**
     * 更新用户配置项
     * 根据配置项ID更新用户配置项内容
* @param requestParameters
     */
    userSettingPut(requestParameters: UserSettingPutRequestParams, extraHttpRequestParams?: any): Observable<BooleanApiResponse>;

    /**
     * 获取用户配置列表
     * 根据用户ID、配置项代码和标签获取用户配置列表
* @param requestParameters
     */
    userSettings(requestParameters: UserSettingsRequestParams, extraHttpRequestParams?: any): Observable<UserSettingListApiResponse>;

}
